### ISSUE TITLE
Remove My Code

### ISSUE THREAD

**Issue by Savnith** [LambdaMC-Dev/LambdaMC-Master#6]
Remove my code or we are going to have some problems.

**Comment by pramire** [comment]
You've been reported for pladherism of code as you passed the code of the TFM 4.3 code as your own. I didn't remove the code because it was yours, I removed it because it was stolen.

**Comment by mayokek** [comment]
And just to add on here, he had copied some code from https://github.com/LegendIsAwesomes/FreedomHostingMod (orginially created by tylerhyperHD)
